const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Behaviors.Timer,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Plugins.shadowlight,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Cnds.PickParent,
		C3.Behaviors.Pin.Acts.PinByImagePoint
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{LanguageIcon: 0},
	{Touch: 0},
	{LanguageBackgroundFade: 0},
	{LanguageSelectButton: 0},
	{TransitionSprite: 0},
	{Timer: 0},
	{TouchSwipeDetector: 0},
	{DragDrop: 0},
	{MainMenuBackgroundDragNDrop: 0},
	{Sine: 0},
	{MainMenuThemeText: 0},
	{LessonButton: 0},
	{MainUITopBackground: 0},
	{LanguageBackground1: 0},
	{LanguageBackground2: 0},
	{LanguageBackground3: 0},
	{LanguageButton: 0},
	{Pin: 0},
	{LanguageButtonText: 0},
	{ShadowLight: 0},
	{Browser: 0},
	{LanguageSelected: 0},
	{Language: 0},
	{NextY: 0},
	{NextX: 0},
	{End: 0}
];

self.InstanceType = {
	LanguageIcon: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	LanguageBackgroundFade: class extends self.ISpriteInstance {},
	LanguageSelectButton: class extends self.ISpriteInstance {},
	TransitionSprite: class extends self.ISpriteInstance {},
	TouchSwipeDetector: class extends self.ISpriteInstance {},
	MainMenuBackgroundDragNDrop: class extends self.ISpriteInstance {},
	MainMenuThemeText: class extends self.ITextInstance {},
	LessonButton: class extends self.ISpriteInstance {},
	MainUITopBackground: class extends self.ISpriteInstance {},
	LanguageBackground1: class extends self.ISpriteInstance {},
	LanguageBackground2: class extends self.ISpriteInstance {},
	LanguageBackground3: class extends self.ISpriteInstance {},
	LanguageButton: class extends self.ISpriteInstance {},
	LanguageButtonText: class extends self.ITextInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	Browser: class extends self.IInstance {}
}