const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Behaviors.Timer,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Plugins.Browser,
		C3.Plugins.Dictionary,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Cnds.PickParent,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.InstanceSignal,
		C3.Plugins.Sprite.Cnds.OnInstanceSignal,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Sprite.Acts.AddChild
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{LanguageIcon: 0},
	{Touch: 0},
	{LanguageBackgroundFade: 0},
	{LanguageSelectButton: 0},
	{Timer: 0},
	{TransitionSprite: 0},
	{NewY: 0},
	{OldY: 0},
	{SwipeSpeed: 0},
	{IsMoving: 0},
	{DragDrop: 0},
	{MainMenuBackgroundDragNDrop: 0},
	{Sine: 0},
	{MainThemeText: 0},
	{PoppedUp: 0},
	{LessonType: 0},
	{Done: 0},
	{LayoutTransitionName: 0},
	{Num: 0},
	{LessonButton: 0},
	{LanguageBackground: 0},
	{LanguageBackgroundUp: 0},
	{LanguageButton: 0},
	{Pin: 0},
	{LanguageButtonText: 0},
	{Browser: 0},
	{LanguageBackgroundMiddle: 0},
	{LanguageBackgroundBottom: 0},
	{LanguageMenuTopText: 0},
	{DebugText: 0},
	{MainLessonsBackgroundUp: 0},
	{LanguageDictionary: 0},
	{Theme: 0},
	{MainLessonsThemeBg: 0},
	{LessonText: 0},
	{LanguageSelected: 0},
	{Language: 0},
	{NextY: 0},
	{NextX: 0},
	{NextTimer: 0},
	{End: 0},
	{TransitionLayoutName: 0},
	{MinY: 0},
	{MaxY: 0}
];

self.InstanceType = {
	LanguageIcon: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	LanguageBackgroundFade: class extends self.ISpriteInstance {},
	LanguageSelectButton: class extends self.ISpriteInstance {},
	TransitionSprite: class extends self.ISpriteInstance {},
	MainMenuBackgroundDragNDrop: class extends self.ISpriteInstance {},
	MainThemeText: class extends self.ITextInstance {},
	LessonButton: class extends self.ISpriteInstance {},
	LanguageBackground: class extends self.ISpriteInstance {},
	LanguageBackgroundUp: class extends self.ISpriteInstance {},
	LanguageButton: class extends self.ISpriteInstance {},
	LanguageButtonText: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	LanguageBackgroundMiddle: class extends self.ISpriteInstance {},
	LanguageBackgroundBottom: class extends self.ISpriteInstance {},
	LanguageMenuTopText: class extends self.ITextInstance {},
	DebugText: class extends self.ITextInstance {},
	MainLessonsBackgroundUp: class extends self.ISpriteInstance {},
	LanguageDictionary: class extends self.IDictionaryInstance {},
	MainLessonsThemeBg: class extends self.ISpriteInstance {},
	LessonText: class extends self.ITextInstance {}
}